name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar Cobra
        uses: Platane/snk@v3
        with:
          github_user_name: layssasuelen03-creator
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?color_snake=00BFFF&color_dots=#0d1117,#003d1a,#006830,#00a050,#00d468&palette=github-dark
            dist/github-contribution-grid-snake.svg?color_snake=00BFFF

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}